### PR TITLE
Return more attributes from IMDBW and TMDBW

### PR DESCRIPTION
**Pull request by Dexterp37**
This adds the "cast", "directors", "writers", "plot" to
the IMDB scraper and fixes "overview" to correctly return
the plot overview rather than the full plot.

This also adds "runtime" to TMDB and renames "language" to
"languages" so that the key name matches the one returned
from IMDB.

Moreover, this PR sorts the attributes returned by get_movie
for easier lookup when reading the code :)

### CODE REVIEW

**Comment by Dexterp37** [comment]
I've not pushed directly to master as there might be something else we'd want to add for *IMDB*. Here's the full list of attributes returned for each movie (in **bold** what we're currently returning):

- 'music department'
- 'sound crew'
- 'camera and electrical department'
- 'distributors' 
- 'rating'
- 'runtimes' 
- 'make up'
- **'year'** 
- 'production design'
- 'miscellaneous crew'
- 'color info'
- 'languages' 
- 'votes'
- 'producer' 
- **'title'** 
- 'assistant director'
- **'writer'** 
- 'production manager'
- 'casting director'
- 'visual effects'
- 'top 250 rank'
- 'set decoration'
- 'editor'
- 'certificates'
- 'costume department'
- 'country codes'
- 'language codes'
- 'cover url'
- 'special effects department'
- 'special effects companies'
- 'sound mix'
- 'location management'
- **'genres'**
- 'production companies'
- 'stunt performer'
- 'miscellaneous companies'
- 'cinematographer'
- 'art direction'
- 'akas'
- 'aspect ratio'
- **'director'**
- 'kind'
- 'art department'
- 'countries'
- 'transportation department'
- **'plot outline'**
- **'plot'**
- **'cast'**
- 'editorial department'
- 'canonical title'
- 'long imdb title'
- 'long imdb canonical title'
- 'smart canonical title'
- 'smart long imdb canonical title'
- 'full-size cover url'

This doesn't mean that all movies will return sane data for these attributes :(

**Comment by vitillo** [comment]
Maybe it makes sense to add also:
- producer
- assistant director
- visual effects

**Comment by Dexterp37** [comment]
@vitillo this is RFAL/good to merge.

**Comment by vitillo** [comment]
LGTM, thanks!

**Pull request merged**
